"""[init]

Revision ID: 8bf7bb642fb9
Revises: 
Create Date: 2026-02-10 19:17:31.193444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf7bb642fb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('participant_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_table('wallet',
    sa.Column('wallet', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.JSON(), nullable=True),
    sa.Column('blockchain', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('wallet')
    )
    op.create_table('invoice',
    sa.Column('invoice_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wallet', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('cy', sa.String(length=255), nullable=True),
    sa.Column('quantum', sa.DECIMAL(), nullable=True),
    sa.Column('fee', sa.DECIMAL(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'payed', 'expired', name='payment_status'), server_default='waiting', nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.ForeignKeyConstraint(['wallet'], ['wallet.wallet'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('purchaser', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('salesman', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'fetch', 'payed', 'expired', name='swap_status'), server_default='waiting', nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ),
    sa.ForeignKeyConstraint(['purchaser'], ['participant.participant_id'], ),
    sa.ForeignKeyConstraint(['salesman'], ['participant.participant_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('invoice')
    op.drop_table('wallet')
    op.drop_table('participant')
    # ### end Alembic commands ###
