"""[empty]

Revision ID: ec8967b99f1e
Revises: fc411186162b
Create Date: 2026-02-16 18:20:38.495436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8967b99f1e'
down_revision: Union[str, None] = 'fc411186162b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('entity_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'entity_id')
    # ### end Alembic commands ###
