"""[empty]

Revision ID: fc411186162b
Revises: 4d853aa3cc16
Create Date: 2026-02-16 13:56:03.279944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc411186162b'
down_revision: Union[str, None] = '4d853aa3cc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('channel_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('manager', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('wallet', sa.String(length=255), nullable=True),
    sa.Column('entity', sa.JSON(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.ForeignKeyConstraint(['manager'], ['participant.participant_id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    # ### end Alembic commands ###
